# Generated by Django 3.1.4 on 2021-01-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delivery_address_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_address',
            name='d_primary',
            field=models.BooleanField(default=False),
        ),
    ]
