# Generated by Django 3.1.4 on 2021-01-23 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_delivery_address_d_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_payed',
            name='d_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.delivery_address'),
        ),
    ]
