# Generated by Django 3.1.4 on 2021-01-28 06:37

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_product_payed_d_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='images',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[1024, 768], upload_to='uploads/%Y/%m/%d'),
        ),
    ]
