# Generated by Django 3.1.4 on 2021-01-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210123_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_address',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
