# Generated by Django 3.1.4 on 2021-01-29 05:03

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20210128_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='images',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[300, 800], upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.RemoveField(
            model_name='paytrack',
            name='item',
        ),
        migrations.AddField(
            model_name='paytrack',
            name='item',
            field=models.ManyToManyField(to='app1.product_payed'),
        ),
    ]
