# Generated by Django 3.1.4 on 2021-01-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20210129_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytrack',
            name='prodcut_data',
            field=models.ManyToManyField(to='app1.product_payed'),
        ),
        migrations.RemoveField(
            model_name='paytrack',
            name='item',
        ),
        migrations.AddField(
            model_name='paytrack',
            name='item',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
