# Generated by Django 3.1.4 on 2021-07-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20210714_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_payed',
            name='delivery_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
