# Generated by Django 3.1.4 on 2021-07-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_product_payed_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytrack',
            name='delivery_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
